import type { FileProxySupport } from '../../application/file-proxy-support.js';
import { logError, sanitizeLogValue } from '../../observability/logger.js';
import { requireAuthenticatedSession } from '../require-authenticated-session.js';
import { asBackendRuntimeContext } from '../runtime-context.js';
import type { BackendServices } from '../services.js';
import type { BackendApp } from '../types.js';

export const installFileRoutes = (
  app: BackendApp,
  services: BackendServices,
  fileProxySupport: FileProxySupport,
): void => {
  // Upload a file to OpenAI via the backend (proxies multipart form data)
  app.post('/v1/files/upload', async (context) => {
    const session = await requireAuthenticatedSession(context, services);
    const env = asBackendRuntimeContext(context.env);

    const formData = await context.req.formData();
    const file = formData.get('file') as File | null;
    const purpose = (formData.get('purpose') as string) ?? 'user_data';

    if (!file) {
      return context.json({ error: 'file_required' }, 400);
    }

    const apiKey = await fileProxySupport.loadApiKey(env, session.userId);

    const openAIForm = new FormData();
    openAIForm.append('file', file, file.name);
    openAIForm.append('purpose', purpose);

    const openAIResponse = await fetch('https://api.openai.com/v1/files', {
      body: openAIForm,
      headers: { Authorization: `Bearer ${apiKey}` },
      method: 'POST',
    });

    if (!openAIResponse.ok) {
      const errorText = await openAIResponse.text();
      logError('openai_file_upload_failed', {
        errorMessage: sanitizeLogValue(errorText),
        userId: session.userId,
      });
      return context.json({ error: 'openai_file_upload_failed' }, 502);
    }

    const result = (await openAIResponse.json()) as {
      bytes: number;
      filename: string;
      id: string;
    };
    return context.json({ bytes: result.bytes, fileId: result.id, filename: result.filename }, 201);
  });

  // Download a file generated by code interpreter (sandbox file proxy)
  app.get('/v1/files/:fileId/content', async (context) => {
    const session = await requireAuthenticatedSession(context, services);
    const env = asBackendRuntimeContext(context.env);
    const fileId = context.req.param('fileId');
    const containerId = context.req.query('container_id') ?? null;

    const apiKey = await fileProxySupport.loadApiKey(env, session.userId);

    const urls = containerId
      ? [
          `https://api.openai.com/v1/containers/${containerId}/files/${fileId}/content`,
          `https://api.openai.com/v1/files/${fileId}/content`,
        ]
      : [`https://api.openai.com/v1/files/${fileId}/content`];

    for (const url of urls) {
      try {
        const openAIResponse = await fetch(url, {
          headers: { Authorization: `Bearer ${apiKey}` },
        });
        if (openAIResponse.ok && openAIResponse.body) {
          return new Response(openAIResponse.body, {
            headers: {
              'Content-Disposition':
                openAIResponse.headers.get('Content-Disposition') ?? 'attachment',
              'Content-Type':
                openAIResponse.headers.get('Content-Type') ?? 'application/octet-stream',
            },
          });
        }
      } catch (error) {
        logError('openai_file_download_attempt_failed', {
          errorMessage: error instanceof Error ? sanitizeLogValue(error.message) : 'unknown_error',
          fileId,
          url: sanitizeLogValue(url),
        });
      }
    }

    return context.json({ error: 'file_not_found' }, 404);
  });
};
