import { makeErrorResponse } from '@glassgpt/backend-contracts';

import type { FileProxySupport } from '../../application/file-proxy-support.js';
import { logError, sanitizeLogValue } from '../../observability/logger.js';
import { requireAuthenticatedSession } from '../require-authenticated-session.js';
import { asBackendRuntimeContext } from '../runtime-context.js';
import type { BackendServices } from '../services.js';
import type { BackendApp } from '../types.js';

export const installFileRoutes = (
  app: BackendApp,
  services: BackendServices,
  fileProxySupport: FileProxySupport,
): void => {
  const makeFileDownloadResponse = (openAIResponse: Response): Response => {
    const headers = new Headers(openAIResponse.headers);

    if (!headers.get('Content-Type')) {
      headers.set('Content-Type', 'application/octet-stream');
    }
    if (!headers.get('Content-Disposition')) {
      headers.set('Content-Disposition', 'attachment');
    }

    return new Response(openAIResponse.body, {
      headers,
      status: openAIResponse.status,
    });
  };

  // Upload a file to OpenAI via the backend (proxies multipart form data)
  app.post('/v1/files/upload', async (context) => {
    const session = await requireAuthenticatedSession(context, services);
    const env = asBackendRuntimeContext(context.env);

    const formData = await context.req.formData();
    const file = formData.get('file') as File | null;
    const purpose = (formData.get('purpose') as string) ?? 'user_data';

    if (!file) {
      const requestId = context.get('requestId');
      return context.json(
        makeErrorResponse('file_required', requestId, { code: 'invalid_request' }),
        400,
      );
    }

    const apiKey = await fileProxySupport.loadApiKey(env, session.userId);

    const openAIForm = new FormData();
    openAIForm.append('file', file, file.name);
    openAIForm.append('purpose', purpose);

    const openAIResponse = await fetch('https://api.openai.com/v1/files', {
      body: openAIForm,
      headers: { Authorization: `Bearer ${apiKey}` },
      method: 'POST',
    });

    if (!openAIResponse.ok) {
      const errorText = await openAIResponse.text();
      const requestId = context.get('requestId');
      logError('openai_file_upload_failed', {
        errorMessage: sanitizeLogValue(errorText),
        requestId,
        userId: session.userId,
      });
      return context.json(makeErrorResponse('openai_file_upload_failed', requestId), 502);
    }

    const result = (await openAIResponse.json()) as {
      bytes: number;
      filename: string;
      id: string;
    };
    return context.json({ bytes: result.bytes, fileId: result.id, filename: result.filename }, 201);
  });

  // Download a file generated by code interpreter (sandbox file proxy)
  app.get('/v1/files/:fileId/content', async (context) => {
    const session = await requireAuthenticatedSession(context, services);
    const env = asBackendRuntimeContext(context.env);
    const fileId = context.req.param('fileId');
    const containerId = context.req.query('container_id') ?? null;

    const apiKey = await fileProxySupport.loadApiKey(env, session.userId);

    const encodedFileId = encodeURIComponent(fileId);
    const urls = containerId
      ? [
          `https://api.openai.com/v1/containers/${encodeURIComponent(containerId)}/files/${encodedFileId}/content`,
          `https://api.openai.com/v1/files/${encodedFileId}/content`,
        ]
      : [`https://api.openai.com/v1/files/${encodedFileId}/content`];

    let lastOpenAIResponse: Response | null = null;
    let lastHardErrorResponse: Response | null = null;
    for (const url of urls) {
      try {
        const openAIResponse = await fetch(url, {
          headers: { Authorization: `Bearer ${apiKey}` },
        });
        if (openAIResponse.ok && openAIResponse.body) {
          return makeFileDownloadResponse(openAIResponse);
        }
        if (openAIResponse.status === 404 || openAIResponse.status === 410) {
          lastOpenAIResponse = openAIResponse;
        } else {
          lastHardErrorResponse = openAIResponse;
        }
      } catch (error) {
        const requestId = context.get('requestId');
        logError('openai_file_download_attempt_failed', {
          errorMessage: error instanceof Error ? sanitizeLogValue(error.message) : 'unknown_error',
          fileId,
          requestId,
          url: sanitizeLogValue(url),
        });
      }
    }

    const requestId = context.get('requestId');

    if (lastHardErrorResponse) {
      return new Response(lastHardErrorResponse.body, {
        headers: new Headers(lastHardErrorResponse.headers),
        status: lastHardErrorResponse.status,
      });
    }

    if (lastOpenAIResponse) {
      return context.json(
        makeErrorResponse('file_not_found', requestId, { code: 'not_found' }),
        404,
      );
    }

    return context.json(makeErrorResponse('file_not_found', requestId, { code: 'not_found' }), 404);
  });
};
