import Foundation

@MainActor
public extension BackendClient {
    /// Uploads a file to OpenAI through the backend proxy.
    /// Returns the OpenAI file ID on success.
    func uploadFile(
        data: Data,
        filename: String,
        mimeType: String
    ) async throws -> String {
        try await refreshSessionIfNeeded(for: .required)

        let url = environment.baseURL.appendingPathComponent("/v1/files/upload")
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.timeoutInterval = 120

        let boundary = UUID().uuidString
        request.setValue(
            "multipart/form-data; boundary=\(boundary)",
            forHTTPHeaderField: "Content-Type"
        )
        if let auth = makeAuthorizationHeader(sessionStore: sessionStore) {
            request.setValue(auth, forHTTPHeaderField: "Authorization")
        }
        if let appVersion = environment.appVersion as String? {
            request.setValue(appVersion, forHTTPHeaderField: backendAppVersionHeaderField)
        }

        var body = Data()
        body.append(Data("--\(boundary)\r\n".utf8))
        body.append(Data("Content-Disposition: form-data; name=\"file\"; filename=\"\(filename)\"\r\n".utf8))
        body.append(Data("Content-Type: \(mimeType)\r\n\r\n".utf8))
        body.append(data)
        body.append(Data("\r\n--\(boundary)\r\n".utf8))
        body.append(Data("Content-Disposition: form-data; name=\"purpose\"\r\n\r\n".utf8))
        body.append(Data("user_data".utf8))
        body.append(Data("\r\n--\(boundary)--\r\n".utf8))
        request.httpBody = body

        let (responseData, response) = try await urlSession.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse,
              (200 ..< 300).contains(httpResponse.statusCode)
        else {
            throw BackendAPIError.networkFailure(
                String(data: responseData, encoding: .utf8) ?? "File upload failed"
            )
        }

        struct UploadResponse: Decodable {
            let fileId: String
        }

        let result = try JSONDecoder().decode(UploadResponse.self, from: responseData)
        return result.fileId
    }

    /// Downloads a file generated by code interpreter through the backend proxy.
    func downloadGeneratedFile(
        fileId: String,
        containerId: String?
    ) async throws -> (data: Data, contentType: String?) {
        try await refreshSessionIfNeeded(for: .required)

        let url = try makeURL(
            path: "/v1/files/\(fileId)/content",
            queryItems: containerId.map { [URLQueryItem(name: "container_id", value: $0)] } ?? []
        )
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.timeoutInterval = 60
        if let auth = makeAuthorizationHeader(sessionStore: sessionStore) {
            request.setValue(auth, forHTTPHeaderField: "Authorization")
        }
        if let appVersion = environment.appVersion as String? {
            request.setValue(appVersion, forHTTPHeaderField: backendAppVersionHeaderField)
        }

        let (data, response) = try await urlSession.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse,
              (200 ..< 300).contains(httpResponse.statusCode)
        else {
            throw BackendAPIError.networkFailure("File download failed")
        }
        let contentType = httpResponse.value(forHTTPHeaderField: "Content-Type")
        return (data: data, contentType: contentType)
    }
}
