import Foundation

@MainActor
public extension BackendClient {
    /// Uploads a file to OpenAI through the backend proxy.
    /// Returns the OpenAI file ID on success.
    func uploadFile(
        data: Data,
        filename: String,
        mimeType: String
    ) async throws -> String {
        let path = "/v1/files/upload"
        try await refreshSessionIfNeeded(for: .required)

        let url = environment.baseURL.appendingPathComponent(path)
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.timeoutInterval = 120

        let boundary = UUID().uuidString
        request.setValue(
            "multipart/form-data; boundary=\(boundary)",
            forHTTPHeaderField: "Content-Type"
        )
        if let auth = makeAuthorizationHeader(sessionStore: sessionStore) {
            request.setValue(auth, forHTTPHeaderField: "Authorization")
        }
        if let appVersion = environment.appVersion as String? {
            request.setValue(appVersion, forHTTPHeaderField: backendAppVersionHeaderField)
        }
        request.setValue(UUID().uuidString, forHTTPHeaderField: "X-Request-ID")

        var body = Data()
        body.append(Data("--\(boundary)\r\n".utf8))
        body.append(Data("Content-Disposition: form-data; name=\"file\"; filename=\"\(filename)\"\r\n".utf8))
        body.append(Data("Content-Type: \(mimeType)\r\n\r\n".utf8))
        body.append(data)
        body.append(Data("\r\n--\(boundary)\r\n".utf8))
        body.append(Data("Content-Disposition: form-data; name=\"purpose\"\r\n\r\n".utf8))
        body.append(Data("user_data".utf8))
        body.append(Data("\r\n--\(boundary)--\r\n".utf8))
        request.httpBody = body

        let requestId = request.value(forHTTPHeaderField: "X-Request-ID")
        BackendNetworkLogger.logRequest(method: "POST", path: path, requestId: requestId)
        let requestStart = ContinuousClock.now
        let responseData: Data
        let response: URLResponse
        do {
            (responseData, response) = try await urlSession.data(for: request)
        } catch {
            BackendNetworkLogger.logError(method: "POST", path: path, error: error, requestId: requestId)
            throw error
        }
        guard let httpResponse = response as? HTTPURLResponse else {
            throw BackendAPIError.invalidResponse
        }
        BackendNetworkLogger.logResponse(
            method: "POST",
            path: path,
            statusCode: httpResponse.statusCode,
            startTime: requestStart,
            requestId: requestId
        )
        guard (200 ..< 300).contains(httpResponse.statusCode) else {
            throw BackendAPIError.networkFailure(
                String(data: responseData, encoding: .utf8) ?? "File upload failed"
            )
        }

        struct UploadResponse: Decodable {
            let fileId: String
        }

        let result = try JSONDecoder().decode(UploadResponse.self, from: responseData)
        return result.fileId
    }

    /// Downloads a file generated by code interpreter through the backend proxy.
    func downloadGeneratedFile(
        fileId: String,
        containerId: String?
    ) async throws -> (data: Data, contentType: String?) {
        let path = "/v1/files/\(fileId)/content"
        let queryItems = containerId.map { [URLQueryItem(name: "container_id", value: $0)] } ?? []
        let (data, httpResponse) = try await execute(
            path: path,
            method: "GET",
            body: Data?.none,
            authorizationMode: .required,
            queryItems: queryItems,
            allowRefreshRetry: true
        )
        let contentType = httpResponse.value(forHTTPHeaderField: "Content-Type")
        return (data: data, contentType: contentType)
    }
}
