// swift-tools-version: 6.2

import PackageDescription

let boundaryTargets: [Target] = [
    .target(
        name: "ChatDomain",
        path: "Sources/ChatDomain",
        resources: [.process("ChatDomain.docc")],
    ),
    .target(
        name: "AITransportContracts",
        dependencies: ["ChatDomain"],
        path: "Sources/AITransportContracts",
        resources: [.process("AITransportContracts.docc")],
    ),
    .target(
        name: "ChatPersistenceContracts",
        dependencies: ["ChatDomain"],
        path: "Sources/ChatPersistenceContracts",
    ),
    .target(
        name: "ChatPersistenceCore",
        dependencies: ["ChatDomain"],
        path: "Sources/ChatPersistenceCore",
    ),
    .target(
        name: "ChatPersistenceSwiftData",
        dependencies: [
            "ChatDomain",
            "ChatPersistenceContracts",
            "ChatPersistenceCore",
            "OpenAITransport",
        ],
        path: "Sources/ChatPersistenceSwiftData",
    ),
    .target(
        name: "OpenAITransport",
        dependencies: ["ChatDomain", "AITransportContracts"],
        path: "Sources/OpenAITransport",
        resources: [.process("OpenAITransport.docc")],
    ),
    .target(
        name: "GeneratedFilesCore",
        dependencies: ["ChatDomain"],
        path: "Sources/GeneratedFilesCore",
    ),
    .target(
        name: "GeneratedFilesInfra",
        dependencies: [
            "ChatDomain",
            "GeneratedFilesCore",
            "OpenAITransport",
        ],
        path: "Sources/GeneratedFilesInfra",
    ),
    .target(
        name: "ChatRuntimeModel",
        dependencies: ["ChatDomain"],
        path: "Sources/ChatRuntimeModel",
    ),
    .target(
        name: "ChatRuntimePorts",
        dependencies: [
            "ChatDomain",
            "ChatPersistenceContracts",
            "GeneratedFilesCore",
            "ChatRuntimeModel",
        ],
        path: "Sources/ChatRuntimePorts",
    ),
    .target(
        name: "ChatRuntimeWorkflows",
        dependencies: [
            "ChatDomain",
            "AITransportContracts",
            "ChatRuntimeModel",
            "ChatRuntimePorts",
            "OpenAITransport",
        ],
        path: "Sources/ChatRuntimeWorkflows",
        resources: [.process("ChatRuntimeWorkflows.docc")],
    ),
    .target(
        name: "ChatApplication",
        dependencies: [
            "ChatDomain",
            "AITransportContracts",
            "ChatPersistenceContracts",
            "ChatPersistenceCore",
            "ChatRuntimeModel",
            "ChatRuntimePorts",
            "ChatRuntimeWorkflows",
        ],
        path: "Sources/ChatApplication",
    ),
    .target(
        name: "ChatPresentation",
        dependencies: [
            "ChatDomain",
            "GeneratedFilesCore",
            "ChatApplication",
        ],
        path: "Sources/ChatPresentation",
    ),
    .target(
        name: "ChatUIComponents",
        path: "Sources/ChatUIComponents",
        resources: [
            .process("Resources"),
        ],
    ),
    .target(
        name: "NativeChatUI",
        dependencies: [
            "ChatDomain",
            "ChatPresentation",
            "ChatUIComponents",
        ],
        path: "Sources/NativeChatUI",
    ),
    .target(
        name: "NativeChatComposition",
        dependencies: [
            "ChatDomain",
            "ChatPersistenceContracts",
            "ChatPersistenceCore",
            "ChatPersistenceSwiftData",
            "OpenAITransport",
            "GeneratedFilesCore",
            "GeneratedFilesInfra",
            "ChatRuntimeModel",
            "ChatRuntimePorts",
            "ChatRuntimeWorkflows",
            "ChatApplication",
            "ChatPresentation",
            "ChatUIComponents",
            "NativeChatUI",
        ],
        path: "Sources/NativeChatComposition",
    ),
    .target(
        name: "NativeChat",
        dependencies: [
            "ChatPersistenceSwiftData",
            "NativeChatComposition",
        ],
        path: "Sources/NativeChat",
    ),
    .target(
        name: "NativeChatUITestSupport",
        dependencies: [
            "ChatDomain",
            "ChatPersistenceCore",
            "ChatPersistenceSwiftData",
            "ChatPresentation",
            "GeneratedFilesCore",
            "GeneratedFilesInfra",
            "OpenAITransport",
            "NativeChatComposition",
        ],
        path: "Support/NativeChatUITestSupport",
    ),
]

let package = Package(
    name: "NativeChat",
    platforms: [
        .iOS("26.0"),
        .macOS("15.0"),
    ],
    products: [
        .library(
            name: "NativeChat",
            targets: ["NativeChat"],
        ),
        .library(
            name: "NativeChatUITestSupport",
            targets: ["NativeChatUITestSupport"],
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/pointfreeco/swift-snapshot-testing",
            from: "1.17.0",
        ),
    ],
    targets: boundaryTargets + [
        .testTarget(
            name: "NativeChatArchitectureTests",
            dependencies: [
                "ChatDomain",
                "AITransportContracts",
                "ChatPersistenceContracts",
                "ChatPersistenceCore",
                "ChatPersistenceSwiftData",
                "OpenAITransport",
                "GeneratedFilesCore",
                "GeneratedFilesInfra",
                "ChatRuntimeModel",
                "ChatRuntimePorts",
                "ChatRuntimeWorkflows",
                "ChatApplication",
                "ChatPresentation",
                "ChatUIComponents",
                "NativeChatUI",
                "NativeChatComposition",
                "NativeChat",
                "NativeChatUITestSupport",
            ],
            path: "Tests/NativeChatArchitectureTests",
        ),
        .testTarget(
            name: "NativeChatSwiftTests",
            dependencies: [
                "ChatDomain",
                "AITransportContracts",
                "ChatPersistenceContracts",
                "ChatPersistenceCore",
                "ChatPersistenceSwiftData",
                "ChatRuntimeModel",
                "ChatRuntimePorts",
                "ChatRuntimeWorkflows",
                "ChatApplication",
                "ChatPresentation",
                "ChatUIComponents",
                "NativeChatUI",
                "OpenAITransport",
                "GeneratedFilesCore",
                "GeneratedFilesInfra",
                "NativeChatComposition",
                "NativeChatUITestSupport",
                .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
            ],
            path: "Tests/NativeChatSwiftTests",
        ),
        .testTarget(
            name: "NativeChatTests",
            dependencies: [
                "ChatDomain",
                "AITransportContracts",
                "ChatPersistenceContracts",
                "ChatPersistenceCore",
                "ChatPersistenceSwiftData",
                "ChatRuntimeModel",
                "ChatRuntimePorts",
                "ChatRuntimeWorkflows",
                "ChatApplication",
                "ChatPresentation",
                "ChatUIComponents",
                "NativeChatUI",
                "NativeChatComposition",
                "NativeChatUITestSupport",
                "OpenAITransport",
                "GeneratedFilesCore",
                "GeneratedFilesInfra",
                .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
            ],
            path: "Tests/NativeChatTests",
            exclude: ["__Snapshots__"],
        ),
    ],
    swiftLanguageModes: [.v6],
)
