/// The available language model variants for chat completions.
public enum ModelType: String, CaseIterable, Identifiable, Codable, Sendable {
    /// Standard GPT-5.4 model.
    case gpt5_4 = "gpt-5.4"
    /// Enhanced GPT-5.4 Pro model with extended reasoning capabilities.
    case gpt5_4_pro = "gpt-5.4-pro"

    /// Stable identifier derived from the raw value.
    public var id: String {
        rawValue
    }

    /// Human-readable model name for display in the UI.
    public var displayName: String {
        switch self {
        case .gpt5_4: "GPT-5.4"
        case .gpt5_4_pro: "GPT-5.4 Pro"
        }
    }

    /// The reasoning effort levels supported by this model.
    public var availableEfforts: [ReasoningEffort] {
        switch self {
        case .gpt5_4:
            [.none, .low, .medium, .high, .xhigh]
        case .gpt5_4_pro:
            [.medium, .high, .xhigh]
        }
    }

    /// The default reasoning effort level for this model.
    public var defaultEffort: ReasoningEffort {
        switch self {
        case .gpt5_4: .high
        case .gpt5_4_pro: .xhigh
        }
    }
}

/// Controls how much computational effort the model spends on reasoning.
public enum ReasoningEffort: String, CaseIterable, Identifiable, Codable, Sendable {
    /// Reasoning is disabled.
    case none
    /// Minimal reasoning effort.
    case low
    /// Moderate reasoning effort.
    case medium
    /// Full reasoning effort.
    case high
    /// Maximum reasoning effort with extended thinking.
    case xhigh

    /// Stable identifier derived from the raw value.
    public var id: String {
        rawValue
    }

    /// Human-readable label for display in the UI.
    public var displayName: String {
        switch self {
        case .none: "None"
        case .low: "Low"
        case .medium: "Medium"
        case .high: "High"
        case .xhigh: "XHigh"
        }
    }

    /// The string value sent to the API for this effort level.
    public var apiValue: String {
        rawValue
    }
}

/// The service tier controlling quality-of-service and pricing for API requests.
public enum ServiceTier: String, CaseIterable, Identifiable, Codable, Sendable {
    /// Standard priority processing.
    case standard = "default"
    /// Flexible priority processing with potential cost savings.
    case flex

    /// Stable identifier derived from the raw value.
    public var id: String {
        rawValue
    }

    /// Human-readable tier name for display in the UI.
    public var displayName: String {
        switch self {
        case .standard: "Standard"
        case .flex: "Flex"
        }
    }
}

/// The role of a participant in a chat conversation.
public enum MessageRole: String, Codable, CaseIterable, Identifiable, Sendable {
    /// A message from the human user.
    case user
    /// A message generated by the assistant.
    case assistant
    /// A system-level instruction or prompt.
    case system

    /// Stable identifier derived from the raw value.
    public var id: String {
        rawValue
    }
}
