import Foundation

/// Describes a file generated by the assistant during a conversation (e.g. code interpreter output).
public struct GeneratedFileDescriptor: Equatable, Hashable, Sendable {
    /// The unique identifier of the file on the API side.
    public let fileID: String
    /// The optional container (sandbox) identifier that owns this file.
    public let containerID: String?
    /// The original filename, if known.
    public let filename: String?
    /// The MIME type of the file, if known.
    public let mediaType: String?

    /// Creates a new generated file descriptor.
    /// - Parameters:
    ///   - fileID: The unique identifier of the file.
    ///   - containerID: The optional container identifier.
    ///   - filename: The original filename.
    ///   - mediaType: The MIME type of the file.
    public init(
        fileID: String,
        containerID: String? = nil,
        filename: String? = nil,
        mediaType: String? = nil
    ) {
        self.fileID = fileID
        self.containerID = Self.normalizedIdentifier(containerID)
        self.filename = Self.normalizedFilename(filename)
        self.mediaType = Self.normalizedMediaType(mediaType)
    }

    /// A composite key suitable for initiating a file download, combining container and file IDs.
    public var downloadKey: String {
        guard let containerID else {
            return fileID
        }

        return "\(containerID):\(fileID)"
    }

    /// The lowercased file extension extracted from ``filename``, or `nil` if unavailable.
    public var pathExtension: String? {
        guard let filename else {
            return nil
        }

        let ext = URL(fileURLWithPath: filename).pathExtension.lowercased()
        return ext.isEmpty ? nil : ext
    }

    /// Whether this file is a PDF based on its extension or media type.
    public var isPDF: Bool {
        pathExtension == "pdf" || mediaType == "application/pdf"
    }

    /// Whether this file is an image based on its extension or media type.
    public var isImage: Bool {
        guard let pathExtension else {
            return mediaType?.hasPrefix("image/") == true
        }

        return Self.imageExtensions.contains(pathExtension)
    }

    private static let imageExtensions: Set = ["png", "jpg", "jpeg", "gif", "webp", "heic"]

    private static func normalizedIdentifier(_ candidate: String?) -> String? {
        guard let candidate else {
            return nil
        }

        let trimmed = candidate.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    private static func normalizedFilename(_ candidate: String?) -> String? {
        guard let candidate else {
            return nil
        }

        let trimmed = candidate.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            return nil
        }

        let component = URL(fileURLWithPath: trimmed).lastPathComponent
        return component.isEmpty ? nil : component
    }

    private static func normalizedMediaType(_ candidate: String?) -> String? {
        guard let candidate else {
            return nil
        }

        let trimmed = candidate.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        return trimmed.isEmpty ? nil : trimmed
    }
}
