import GeneratedFiles

typealias FilePreviewKind = GeneratedFiles.FilePreviewKind
typealias FilePreviewItem = GeneratedFiles.FilePreviewItem
typealias SharedGeneratedFileItem = GeneratedFiles.SharedGeneratedFileItem
