import OpenAITransport

typealias UploadedFileResponseDTO = OpenAITransport.UploadedFileResponseDTO
typealias ResponsesErrorDTO = OpenAITransport.ResponsesErrorDTO
typealias ResponsesTextFragmentDTO = OpenAITransport.ResponsesTextFragmentDTO
typealias ResponsesReasoningDTO = OpenAITransport.ResponsesReasoningDTO
typealias ResponsesAnnotationDTO = OpenAITransport.ResponsesAnnotationDTO
typealias ResponsesContentPartDTO = OpenAITransport.ResponsesContentPartDTO
typealias ResponsesActionDTO = OpenAITransport.ResponsesActionDTO
typealias ResponsesCodeInterpreterOutputDTO = OpenAITransport.ResponsesCodeInterpreterOutputDTO
typealias ResponsesOutputItemDTO = OpenAITransport.ResponsesOutputItemDTO
typealias ResponsesResponseDTO = OpenAITransport.ResponsesResponseDTO
typealias ResponsesStreamEnvelopeDTO = OpenAITransport.ResponsesStreamEnvelopeDTO
